# Generated by Django 4.1 on 2023-04-29 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_rename_payment_id_loanpayment_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loanpayment',
            old_name='id',
            new_name='payment_id',
        ),
    ]
